{% set name = "nbautoexport" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f2a07f1e7b50233ee18e54e67f35fc4986a6714952db082c8a1c4de4179fac95

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nbautoexport=nbautoexport.nbautoexport:app

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jupyter_contrib_nbextensions >=0.5.1
    - nbconvert >=5.6.1
    - packaging
    - pydantic
    - python >=3.6
    - typer >=0.3.0

test:
  imports:
    - nbautoexport
  commands:
    - pip check
    - nbautoexport --help
  requires:
    - pip

about:
  home: https://github.com/drivendataorg/nbautoexport
  summary: Automatically export Jupyter notebooks to various file formats (.py, .html, and more) on save.
  license: MIT
  license_file: LICENSE
  description: |
    nbautoexport automatically exports Jupyter notebooks to various file formats (.py, .html, and more)
    upon save. One great use case is to automatically have script versions of your notebooks to
    facilitate code review commenting.
  doc_url: https://nbautoexport.drivendata.org/
  dev_url: https://github.com/drivendataorg/nbautoexport

extra:
  recipe-maintainers:
    - jayqi
