{% set name = "nbautoexport" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd0fef368c82ab1fb46aea6bc24acc6bf38c06a7598f90c10715d7dfd9e5906f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nbautoexport=nbautoexport.nbautoexport:app

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - nbconvert >=5.6.1
    - nbformat
    - notebook
    - jupyter_core
    - packaging
    - pydantic
    - python >=3.6
    - traitlets
    - typer >=0.3.0

test:
  imports:
    - nbautoexport
  commands:
    - pip check
    - nbautoexport --help
  requires:
    - pip

about:
  home: https://github.com/drivendataorg/nbautoexport
  summary: Automatically export Jupyter notebooks to various file formats (.py, .html, and more) on save.
  license: MIT
  license_file: LICENSE
  description: |
    nbautoexport automatically exports Jupyter notebooks to various file formats (.py, .html, and more)
    upon save. One great use case is to automatically have script versions of your notebooks to
    facilitate code review commenting.
  doc_url: https://nbautoexport.drivendata.org/
  dev_url: https://github.com/drivendataorg/nbautoexport

extra:
  recipe-maintainers:
    - jayqi
