{% set name = "nbautoexport" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3342149ad0a6330b4402d44b94e63bf60d6062b74e31d300e6d1435e990be6ac

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nbautoexport=nbautoexport.nbautoexport:app

requirements:
  host:
    - pdm-pep517
    - pip
    - python {{ python_min }}
  run:
    - nbconvert >=5.6.1
    - nbformat
    - notebook
    - jupyter_core
    - packaging
    - pydantic
    - python >={{ python_min }}
    - traitlets
    - typer >=0.3.0

test:
  imports:
    - nbautoexport
  commands:
    - pip check
    - nbautoexport --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/drivendataorg/nbautoexport
  summary: Automatically export Jupyter notebooks to various file formats (.py, .html, and more) on save.
  license: MIT
  license_file: LICENSE
  description: |
    nbautoexport automatically exports Jupyter notebooks to various file formats (.py, .html, and more)
    upon save. One great use case is to automatically have script versions of your notebooks to
    facilitate code review commenting.
  doc_url: https://nbautoexport.drivendata.org/
  dev_url: https://github.com/drivendataorg/nbautoexport

extra:
  recipe-maintainers:
    - jayqi
