{% set name = "nbautoexport" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6aee94fb05409b67cc3dae690bbf9c32d05f63a2f6fb4da9231feb6c054e836d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nbautoexport=nbautoexport.nbautoexport:app

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - nbconvert >=5.6.1
    - nbformat
    - notebook
    - jupyter_core
    - packaging
    - pydantic
    - python >=3.7
    - traitlets
    - typer >=0.3.0

test:
  imports:
    - nbautoexport
  commands:
    - pip check
    - nbautoexport --help
  requires:
    - pip

about:
  home: https://github.com/drivendataorg/nbautoexport
  summary: Automatically export Jupyter notebooks to various file formats (.py, .html, and more) on save.
  license: MIT
  license_file: LICENSE
  description: |
    nbautoexport automatically exports Jupyter notebooks to various file formats (.py, .html, and more)
    upon save. One great use case is to automatically have script versions of your notebooks to
    facilitate code review commenting.
  doc_url: https://nbautoexport.drivendata.org/
  dev_url: https://github.com/drivendataorg/nbautoexport

extra:
  recipe-maintainers:
    - jayqi
